name: Checks
on: [pull_request]
jobs:
  bundle_check:
    name: report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install NPM dependencies
        uses: bahmutov/npm-install@v1
      - name: Run build and report bundle size
        env:
          PT_PROJECT_TOKEN: ${{ secrets.PT_PROJECT_TOKEN }}
        run: npm run build
  accessibility_job:
    runs-on: ubuntu-latest
    name: Run accessibility tests
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install NPM dependencies
        uses: bahmutov/npm-install@v1
      - name: Run build
        run: npm run build
      - name: Run a11y tests
        uses: omboo/a11y-action@master
        with:
          urls: "http://localhost:3000"
          fail-on-error: true
          start-command: "npm start"
          wait-on: "http://localhost:3000"